type MusicUploadRes {
  ok: Boolean!
  error: String
}
type Mutation {
  musicUpload(
    address: [String!]!
    caption: [String!]!
    volume: [Int!]!
    directory_id: [Int!]!
    type: [String]
  ): MusicUploadRes!
}
