type VideoUploadRes {
  ok: Boolean!
  error: String
}
type Mutation {
  videoUpload(
    address: [String!]!
    caption: [String!]!
    volume: [Int!]!
    directory_id: [Int!]!
    type: [String]
    thumbnail: [String]
  ): VideoUploadRes!
}
