type Query {
  FileManage(skip: Int, take: Int): mediaVolumeInfo
}
type mediaVolumeInfo {
  images: volumeWithCount
  musics: volumeWithCount
  videos: volumeWithCount
}
type volumeWithCount {
  count: Int
  volume: Int
}
